# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go (b0f11b74-5895-49f3-8500-afc50f7ea996)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -l eastus -n MyResourceGroup'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
